config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index]
  resources :people
   
  root 'users#login'
    
  get 'signup' => "users#new", as: :signup
    
  get 'login' => "users#login", as: :login
    
  post "/login" => "users#authenticate"
    
  delete "logout/:id" => "users#logout", as: :logout
    
  get 'scrape' => "scraper#index", as: :scrape
    
  get 'clear' => "scraper#clear", as: :clear
    
  post "/scrape" => "scraper#scrape"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/scraper.rb
require 'Nokogiri'
require 'HTTParty'
require 'JSON'

class Scraper < ApplicationRecord
    	    
    def self.scrape(page)
		parse_page = Nokogiri::HTML(page)
        pets_array = []
        parse_page.css('.content').css('.rows').css('.result-row').css('.hdrlnk').map do |a|
            post_name = a.text
            pets_array.push(post_name)
        end
        return pets_array
	end
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :first_name, :last_name, :email, :password
	validates_uniqueness_of :email
    
    def self.authenticate(email, password)
		@user = User.find_by_email(email)
		
		if !@user.nil?
			if @user.authenticate(password)
				return @user
			end
		end
		return nil
	end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    
  def require_login
		if !logged_in?
			redirect_to login_path
		end
  end
    
  def current_user
	@user ||= User.where("id=?", session[:user_id]).first
  end
  
  def logged_in?
	!current_user.nil? && !current_user.id.nil?
  end
  
  helper_method :current_user
  helper_method :logged_in?
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :birthdate)
    end
end

app/controllers/scraper_controller.rb
require 'HTTParty'

class ScraperController < ApplicationController
    before_action :require_login
    
    # GET /scraper
    def index
    end
    
    def scrape
        @url = params[:url]
        puts "@url: #{@url}"
        page = HTTParty.get(@url, :verify => false)
        #puts "Page: #{page}"
        @scraper = Scraper.scrape(page)
        puts "Scraper: #{@scraper}"
        render 'index'
    end
    
    def clear
       @scraper = []
       render 'index'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :update, :destroy]

  def login
  end
    
  def authenticate
	@user = User.authenticate(params[:email], params[:password])
	if @user.nil?
		@errors = "Either the email is incorrect, or the password provided is wrong!"
		render :login
	else
		#render :text => @user[0][:id]
		session[:user_id] = @user.id
		redirect_to user_path(@user)
	end
  end
    
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    
  def logout
	session.delete(:user_id)
	redirect_to login_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
		@user ||= User.where("id=?", session[:user_id]).first
	end
	  
	def logged_in?
		!current_user.nil? && !current_user.id.nil?
	end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web Scraper</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'jquery-1.12.3.min', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css"/>
 
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.js"></script>
  </head>

  <body>
      <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <h3 style="margin-top:8px;">Web Scraper <small>A GBB Creations Project</small></h2>
                </div>
                <div class="pull-right">
                    <% if logged_in? %>
                        <input type="hidden" id="user_id" name="user_id" value="<%= current_user.id %>"/>
                    <div class="dropdown" style="margin-top:12px;">
                        <button id="dropdownMenu1" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <%= current_user.first_name %>
                            <span class="caret"></span>
                        </button>

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation" class="divider"></li>
                            <li role="presentation">
								<%= link_to "Scraper", scrape_path, "role" => "menuitem", "tabindex" => "-1" %>
				            </li>
                            <li role="presentation">
                            <%= link_to "Logout", logout_path(current_user), :method => :delete, "role" => "menuitem", "tabindex" => "-1" %>
                            </li>
                        </ul>
                    </div>
                    <% end %>
                </div>
            </div>
      </nav>
      <div class="clear-fix">&nbsp;</div>
      <div class="container">
            <%= yield %>
      </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate, :start_year=>1910, :end_year=>Date.today.year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birthdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.birthdate %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path, class: "btn btn-default" %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @person.birthdate %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/scraper/index.html.erb
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>
<h1>Scraper</h1>
<br/><br/>
<div class="panel">
	<div class="panel-body">
        <%= form_tag({:controller=>'scraper', :action=>'scrape'}, {:class => 'col-md-5'}) do %>
				<div class="form-group">
					<label for="url">Choose a site</label>
					<select class="form-control" id="url" name="url">
                      <option>https://newyork.craigslist.org/search/pet?s=0</option>
                     </select>
                    <br/>
					<input type="submit" class="btn btn-default">&nbsp;
                    <%= link_to 'Clear', clear_path, class: 'btn btn-primary' %>
				</div>
        <% end %>
    </div>
</div>
<% if @scraper.present? then %>
    <div class="panel panel-default">
        <div class="panel-heading"><%= @url %></div>
        <div class="panel-body">
            <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Item</th>
                    </tr>
                </thead>
                <tbody>
                    <% @scraper.each do |pet| %>
                        <tr>
                            <td>
                                <%= pet %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>
<br/><br/>
<div class="panel">
	<div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>First name</th>
              <th>Last name</th>
              <th>Email</th>
              <th>Password</th>
              <th>&nbsp;</th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= user.password %></td>
                <td><%= link_to 'Show', user, class: "btn btn-primary anchor" %>&nbsp;
                    <%= link_to 'Edit', edit_user_path(user), class: "btn btn-warning anchor" %>&nbsp;
                    <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger anchor" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-default anchor" %>

app/views/users/login.erb
<script>
	  $(document).ready(function() {
		$( "#email" ).focus();
	  });
</script>
<div class="header">
  <h1>User Login</h1>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Please sign in:</div>
	<div class="panel-body">
        <% if !@errors.nil? %>
			<div class="alert alert-danger" role="alert"><p><b>Incorrect login:</b></p>
				<ul>
					<li><%= @errors %></li>
				</ul>
			</div>
		<% end %>
        <%= form_tag('/login', class: 'col-md-8 form-horizontal') do %>
			<div class="form-group">
				<label for="email" class="col-md-2 control-label">Email:</label>
				<div class="col-md-4">
					<%= email_field_tag 'email', nil, placeholder: 'email@example.com', class: 'form-control' %>
				</div>
			</div>
			<div class="form-group">
				<label for="password" class="col-md-2 control-label">Password:</label>
				<div class="col-md-4">
					<%= password_field_tag 'password', nil, class: 'form-control' %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-2"></div>
				<div class="col-md-4">
					<%= button_tag "Sign in", data: { disable_with: 'Please wait...' }, class: 'btn btn-default' %>
				</div>
			</div>
		<% end %>   
    </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="header">
  <h1>Users Information</h1>
</div>
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
	<div class="panel-body">
        <p>
          <strong>First name:</strong>
          <%= @user.first_name %>
        </p>

        <p>
          <strong>Last name:</strong>
          <%= @user.last_name %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @user.email %>
        </p>

        <p>
          <strong>Password:</strong>
          <%= @user.password %>
        </p>
    </div>
</div>

<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-warning' %>
<%= link_to 'Back', login_path, class: 'btn btn-default' %>